version: '3'
services:
  jenkins:
    container_name: taller_ci
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  git:
    container_name: git_server
    hostname: gitlab.example.com 
    ports: 
      - "443:443"
      - "80:80"
    restart: always
    volumes: 
      - "$PWD/GITLAB_HOME/config:/etc/gitlab"
      - "$PWD/GITLAB_HOME/logs:/var/log/gitlab"
      - "$PWD/GITLAB_HOME/data:/var/opt/gitlab"
    image: gitlab/gitlab-ee:latest
    networks: 
      - net
networks:
  net: 